### ISSUE TITLE
No test data for NGA extensions

### ISSUE THREAD

**Issue by bradh** [ngageoint/GeoPackage#1]
There are NGA defined extensions that are documented, but the is no representative data that allows testing, or shows the intended use.

**Comment by bosborn** [comment]
Created a rivers GeoPackage demonstrating both extensions.  Added example links to the GeoPackage in the extensions at http://ngageoint.github.io/GeoPackage/docs/extensions/

It would be useful if geopackage.org had examples linked for each gpkg extension.

**Comment by bradh** [comment]
Thanks - appreciated.
