### ISSUE TITLE
Various Java implementations are not distinct

### ISSUE THREAD

**Issue by bradh** [ngageoint/GeoPackage#2]
The first three implementations listed (Java, Core Java, Android) would be easier to understand if the commonality / differences between them were identified.

**Comment by bosborn** [comment]
* Added descriptions on http://ngageoint.github.io/GeoPackage/
* Organized the projects on the README and clarified descriptions

The Core Java project provides Java implementations that are common between the Java and Android projects.  It is not meant to be used directly.

The Java and Android libraries provide the same implementations but specific to either Java or Android.  The Java project provides some command line utilities.  The Android project provides Android specific utilities and app integrations.  Should be fairly straight forward in using one of those two depending on if you are using in an Android application or using as a straight Java library.

Does that help clarify each project's purpose for you?

**Comment by bradh** [comment]
Yes it does. I added a PR for linkage the other way too.

**Comment by bosborn** [comment]
Accepted the PR, thanks.
