### ISSUE TITLE
Invalid geometry for feature id == 4 of table non_linear_geometries of example.gpkg

### ISSUE THREAD

**Issue by rouault** [ngageoint/GeoPackage#7]
http://ngageoint.github.io/GeoPackage/examples/java/example.gpkg has in its non_linear_geometries table for feature of id 4 the following geometry (hexadecimal dump):

47500000000010E600000000
05 <-- MultiLineString
0000000100000000
08 <-- CircularString
00000005C05E96E978D4FDF44047D395810624DDC05E9645A1CAC0834047D3126E978D50C05E9645A1CAC0834047D4395810624EC05E96E978D4FDF44047D4395810624EC05E96E978D4FDF44047D395810624DD

This is a MultiLineString (type = 5) made of a CircularString (type = 8).
This illegal. The value of the top geometry type should MultiCurve = 11.

Found when testing with GDAL GeoPackage driver

**Comment by bosborn** [comment]
MultiCurve is an abstract geometry in both [OGC 06-103r4](http://portal.opengeospatial.org/files/?artifact_id=25355) and [OGC 05-134](http://portal.opengeospatial.org/files/?artifact_id=13228).  Only seems instantiable in the [OGC 06-104r4](http://portal.opengeospatial.org/files/?artifact_id=25354) "SQL option".

```
OGC 06-103r4:

MultiCurve and MultiSurface are introduced as abstract superclasses that generalize the
collection interfaces to handle Curves and Surfaces.

MultiCurve is a non-instantiable class in this standard; it defines a set of methods for its subclasses and is
included for reasons of extensibility.

A MultiLineString is a subtype of the non-instantiable type MultiCurve.
```
MultiLineString is composed of LineStrings.  Child types of LineStrings include Line and LinearRing. CircularString is not mentioned many times in the simple feature specs and is not shown in the class hierarchy.

I assumed CircularString was a child of LineString based upon the simple features specs, JTS, and our SF libraries.  I see it directly under (Simple)Curve in GDAL and a few other SQL based libraries.

An abstract (uninstantiable) MultiCurve geometry composed of Curve inheriting CircularStrings doesn't seem valid or supported by the OGC documentation.  Even if CircularString was a sibling to LineString, it still seems like a MultiLineString would be required to contain them, not the abstract MultiCurve.

![image](https://user-images.githubusercontent.com/11667761/210323202-6f26e7c3-2a02-4076-a02f-76a5deb22620.png)

The GeoPackage spec does [normatively state in the annex](https://www.geopackage.org/spec/#geometry_types):

`CURVE subtypes are LINESTRING, CIRCULARSTRING and COMPOUNDCURVE.`

It seems that this would need to indicate a MultiLineString can contain either LineStrings or CircularStrings.

OR, if CircularStrings are LineStrings, the spec should be changed to:

```
CURVE subtypes are LINESTRING and COMPOUNDCURVE.

LINESTRING subtypes are CIRCULARSTRING.
```

The GeoPackage Geometry is encoded as OGC 06-103r4, not a SQL geometry encoding such as SpatialLite.  It should follow OGC simple features specifications.

![image](https://user-images.githubusercontent.com/11667761/210332783-36cb40d4-8993-40df-8d38-5f4d6b50626b.png)

Though a rare case, I have encountered a 3rd party GeoPackage with this type of WKB before.  I added a case to our GeoPackage example to be sure it was handled.

Do you know of some other spec reference or non GDAL documentation that states it is illegal?  Something isn't lining up correctly between the GeoPackage spec, Simple Features spec, and this issue's claim.

**Comment by bosborn** [comment]
I tracked down a copy of ISO 13249-3 and see what you are saying with the binary.

![Screenshot 2023-01-03 at 3 50 35 AM](https://user-images.githubusercontent.com/11667761/210343773-6d86f554-3b17-4b53-8565-f625f871c7a3.png)

![Screenshot 2023-01-03 at 3 52 08 AM](https://user-images.githubusercontent.com/11667761/210343790-6652748a-8e31-4f52-b1f6-756e8b2c0eaf.png)

![Screenshot 2023-01-03 at 3 56 03 AM](https://user-images.githubusercontent.com/11667761/210343997-ff7ab407-bbc5-46fd-90c9-b27f0edb7345.png)

![Screenshot 2023-01-03 at 3 50 56 AM](https://user-images.githubusercontent.com/11667761/210343804-65a9bec0-16b0-45e9-8682-489e149393f1.png)

![Screenshot 2023-01-03 at 3 53 09 AM](https://user-images.githubusercontent.com/11667761/210343822-f5f84eef-89d7-447e-b1cf-762fcfe3db3e.png)

**Comment by rouault** [comment]
> I tracked down a copy of ISO 13249-3 and see what you are saying with the binary.

indeed, pure OGC specs are behind the state of the art regarding non-linear geometry types. ISO SQL MM Part 3 (13249-3) is what needs to be followed on this, and what the GeoPackage specs refers to.
The omission of CircularString and CompoundCurve in the diagram and text of http://www.geopackage.org/spec130/#sfsql_intro seems to be just an omission, given that they are then mentioned in http://www.geopackage.org/spec130/#geometry_types
